enum ConfigKey {
  //  app
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  VERSION = 'VERSION',

  //  timezone
  TZ = 'TZ',
  DEFAULT_TIMEZONE = 'DEFAULT_TIMEZONE',
  DEFAULT_TIMEZONE_NAME = 'DEFAULT_TIMEZONE_NAME',
  //  API PREFIX URL
  BASE_PATH = 'BASE_PATH',

  //  log
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_ROOT_FOLDER = 'LOG_ROOT_FOLDER',

  //  mongodb
  MONGO_DATABASE_CONNECTION_STRING = 'MONGO_DATABASE_CONNECTION_STRING',
  MONGO_DEBUG = 'MONGO_DEBUG',

  // redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_CACHE_TTL = 'REDIS_CACHE_TTL',
  REDIS_PING_INTERVAL = 'REDIS_PING_INTERVAL',
  REDIS_TLS = 'REDIS_TLS',

  //  cors
  CORS_WHITELIST = 'CORS_WHITELIST',

  // jwt - authentication
  JWT_ACCESS_TOKEN_SECRET_KEY = 'JWT_ACCESS_TOKEN_SECRET_KEY',
  JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN',
  JWT_REFRESH_TOKEN_SECRET_KEY = 'JWT_REFRESH_TOKEN_SECRET_KEY',
  JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN',

  // Google clientId-secret
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',

  //  AWS
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_S3_BUCKET_REGION = 'AWS_S3_BUCKET_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',

  // Mailer
  MAIL_FROM = 'MAIL_FROM',
  MAIL_PORT = 'MAIL_PORT',
  MAIL_USER = 'MAIL_USER',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  MAIL_HOST = 'MAIL_HOST',

  // Frontend
  FRONTEND_DOMAIN = 'FRONTEND_DOMAIN',

  // User
  EXPIRED_ACTIVE_ACCOUNT_HOURS = 'EXPIRED_ACTIVE_ACCOUNT_HOURS',

  // Lesson
  LIMIT_TIME_UPDATE_LESSON = 'LIMIT_TIME_UPDATE_LESSON',
}

export default ConfigKey;
